### ISSUE TITLE
Can't scroll down and can only see down to "Open video when done" and "Ask where to save every time"

### ISSUE THREAD

**Issue by TesterOnTheInternet** [dhsavell/vdcrpt#13]
I can only see down to "Open video when done" and "Ask where to save every time". Also can't scroll down.
![image](https://user-images.githubusercontent.com/113145592/189237438-2e1f9799-5a7e-4d73-b869-a684c6c35d4e.png)

**Comment by branchpanic** [comment]
Right, thanks for reminding me about this, I never actually got around to fixing it. I'll do a quick release that adds scrolling and makes the UI less huge.

![devenv_MUO3mMaAl1](https://user-images.githubusercontent.com/3802908/189544250-e1fae37d-591d-40db-965b-a827e749e3a9.gif)

I'll close this issue once the release is up, I just need to test it on all platforms since I also updated the dependencies.

**Comment by branchpanic** [comment]
Done: https://branchpanic.itch.io/vdcrpt/devlog/426769/vdcrpt-220901-the-window-is-less-huge-now
